<?php


/**
 * Implements preprocess_page().
 */
function sigmagraph_preprocess_page(&$variables) {
  if (drupal_get_path_alias() == 'graph') {
    // Add js
    drupal_add_js(drupal_get_path('module', 'sigmagraph') . '/sigma.min.js',array(
		  'type' => 'file',
		  'scope' => 'footer',
		  'group' => JS_DEFAULT,
		  'every_page' => FALSE,
		  'weight' => 20,
		));
    drupal_add_js(drupal_get_path('module', 'sigmagraph') . '/graph.js',array(
		  'type' => 'file',
		  'scope' => 'footer',
		  'group' => JS_DEFAULT,
		  'every_page' => FALSE,
		  'weight' => 21,
		));    
  }
}




